foo: bar
# setting clent server
server:
  port: 8084
# setting project
info:
  application:
    name: @project.name@
    version: @project.version@
    owner: coison
    author: coison

#  component: center core service
#    默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.j ar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
debug: true

---
# 开发环境
spring:
  profiles: dev
  application:
      name: @project.artifactId@
  http:
      encoding.charset: UTF-8
      encoding.force: true
      encoding:
        enabled: true
  boot:
    admin:
      url: http://localhost:8761  # 服务注册地址
      username: "${security.user.name}"  #These two are needed so that the client
      password: "${security.user.password}" #can register at the protected server api
      client:
        prefer-ip: true # 使用ip-address，而不是被猜测的url中的主机名 它被使用。否则InetAddress.getLocalHost()将使用返回的IP地址。
        enabled: true # 启用S​​pring Boot Admin Client。
        name:  @project.name@ # 要注册的名称
        metadata:
          user.name: "${security.user.name}"  #These two are needed so that the server
          user.password: "${security.user.password}"
#      api-path: "api/applications" # 注册端点的Http路径在您的管理服务器上
#        health-url:  # Client-health-url注册。如果可访问的URL不同（例如Docker），可以被覆盖。在注册表中必须是唯一的
      auto-registration: true   # 如果设置为true，则在应用程序准备就绪后自动计划定期注册应用程序任务
      register-once: true #如果设置为true，客户端将仅注册一个管理服务器（按照定义spring.boot.admin.url）。如果该管理服务器关闭，将自动向下一个管理服务器注册。如果为false，将注册所有管理服务器。
  mvc:
    async:
      request-timeout: -1

#用于提供给监控的上下文URI设置
management:
  security:
    enabled: false
  address: localhost
#Eureka 服务注册与发现
eureka:
  instance:
    healthCheckUrl: true
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
